config_version = "0"

exclude_patterns = [
  "**/.direnv/**",
  "**/.git/**",
  "**/.venv/**",
  "**/__pycache__/**",
  "**/build/**",
  "**/dist/**",
  "**/node_modules/**",
]

test_patterns = [
  "**/test/**",
  "**/tests/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/test_*.*",
]

[smells]
mode = "comment"

[[source]]
name = "default"
default = true

[[plugin]]
name = "bandit"

[[plugin]]
name = "radarlint-python"
mode = "comment"

[[plugin]]
name = "ripgrep"
mode = "comment"

[[plugin]]
name = "ruff"
drivers = ["lint"]

[[plugin]]
name = "shellcheck"

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "yamllint"
